---
language: python
python: "3.7"

sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version

script:
  - ansible-playbook tests/test.yml -i tests/inventory.yml --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/